services:
  # Main Django Web Service (Docker)
  - type: web
    name: event-booking-api
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: event-booking-api.onrender.com
      - key: DB_NAME
        value: events_pq4z
      - key: DB_USER
        value: banta
      - key: DB_PASSWORD
        value: 2fepR2roULpgc15XTxeVx2vfSbSkg2Bv
      - key: DB_HOST
        value: dpg-d2pj25ur433s73dcalj0-a
      - key: DB_PORT
        value: 5432
      - key: REDIS_URL
        sync: false
      - key: TICKETMASTER_API_KEY
        sync: false
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: 587
      - key: EMAIL_USE_TLS
        value: true
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: DEFAULT_FROM_EMAIL
        sync: false
      - key: FRONTEND_URL
        value: https://my-frontend-domain.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://my-frontend-domain.com,https://event-booking-api.onrender.com
      - key: CSRF_TRUSTED_ORIGINS
        value: https://event-booking-api-xf5e.onrender.com,https://my-frontend-domain.com
      - key: SESSION_COOKIE_DOMAIN
        value: .onrender.com
      - key: CSRF_COOKIE_DOMAIN
        value: .onrender.com
    healthCheckPath: /health/
    autoDeploy: true
  