# Generated by Django 5.2.5 on 2025-08-29 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=100, unique=True)),
                ('provider', models.CharField(choices=[('ticketmaster', 'Ticketmaster'), ('seatgeek', 'SeatGeek'), ('eventbrite', 'Eventbrite')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('venue_name', models.CharField(blank=True, max_length=200)),
                ('venue_address', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('ticket_url', models.URLField(blank=True)),
                ('price_range', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('raw_data', models.JSONField(default=dict)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('is_imported', models.BooleanField(default=False)),
                ('imported_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_source', to='events.event')),
            ],
            options={
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['provider'], name='external_ev_provide_0c69e4_idx'), models.Index(fields=['start_time'], name='external_ev_start_t_1a9c14_idx'), models.Index(fields=['is_imported'], name='external_ev_is_impo_5f9f34_idx')],
            },
        ),
    ]
